# Generated by Django 2.2.5 on 2019-11-29 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='person_info',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='账户ID')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='邮箱')),
                ('Sex', models.CharField(max_length=4, verbose_name='性别')),
                ('Name', models.CharField(max_length=30, verbose_name='用户名')),
                ('Password', models.CharField(max_length=30, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='librarian_info',
            fields=[
                ('person_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.person_info')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('idType', models.CharField(max_length=10, verbose_name='证件类型')),
                ('idNumber', models.CharField(max_length=8, verbose_name='证件号码')),
            ],
            bases=('login.person_info',),
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('person_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.person_info')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='姓名')),
                ('phone', models.IntegerField(unique=True, verbose_name='电话')),
                ('max_borrowing', models.IntegerField(default=5, verbose_name='可借数量')),
                ('balance', models.FloatField(default=0.0, verbose_name='余额')),
                ('photo', models.ImageField(blank=True, upload_to='media/zhangli', verbose_name='头像')),
                ('inTime', models.DateField(default='2019-11-16', verbose_name='登记日期')),
                ('status', models.IntegerField(choices=[(0, 'normal'), (-1, 'overdue')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='读者')),
            ],
            options={
                'verbose_name': '读者',
                'verbose_name_plural': '读者',
            },
            bases=('login.person_info',),
        ),
    ]
