# Generated by Django 2.2.5 on 2019-11-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='phone',
            field=models.IntegerField(verbose_name='电话'),
        ),
    ]
