# Generated by Django 2.2.5 on 2019-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191129_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_info',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='邮箱'),
        ),
    ]
