# Generated by Django 2.2.5 on 2019-12-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191129_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_info',
            old_name='Name',
            new_name='IDname',
        ),
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(max_length=16, verbose_name='姓名'),
        ),
    ]
