# Generated by Django 2.2.5 on 2019-12-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20191201_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person_info',
            old_name='IDname',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='person_info',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='电话'),
        ),
    ]
