# Generated by Django 2.2.5 on 2019-12-08 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_auto_20191202_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_info',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='user',
        ),
        migrations.AddField(
            model_name='person_info',
            name='name',
            field=models.CharField(default='testUser', max_length=30, verbose_name='用户姓名'),
        ),
        migrations.AddField(
            model_name='person_info',
            name='user',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='无分组数字图书馆系统用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person_info',
            name='Sex',
            field=models.CharField(choices=[(0, '男'), (1, '女')], max_length=4, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='person_info',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phone',
            field=models.IntegerField(verbose_name='电话'),
        ),
    ]
