# Generated by Django 2.2.5 on 2019-12-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191208_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_info',
            name='name',
            field=models.CharField(max_length=30, verbose_name='用户姓名'),
        ),
    ]
