# Generated by Django 2.2.5 on 2019-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20191208_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian_info',
            name='idNumber',
        ),
        migrations.RemoveField(
            model_name='librarian_info',
            name='idType',
        ),
        migrations.RemoveField(
            model_name='person_info',
            name='email',
        ),
        migrations.AddField(
            model_name='librarian_info',
            name='gonghao',
            field=models.CharField(default='2017141093015', max_length=13, unique=True, verbose_name='馆员工号'),
        ),
        migrations.AddField(
            model_name='reader',
            name='email',
            field=models.EmailField(default='zlscu@163.com', max_length=254, unique=True, verbose_name='邮箱'),
        ),
    ]
