# Generated by Django 2.2.5 on 2019-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20191208_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian_info',
            name='gonghao',
            field=models.CharField(max_length=13, unique=True, verbose_name='馆员工号'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
    ]
