# Generated by Django 2.2.5 on 2019-12-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20191208_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian_info',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/zhangli/librarian', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='person_info',
            name='role',
            field=models.CharField(choices=[(0, 'reader'), (1, 'librarian')], default=0, max_length=4, verbose_name='用户分组'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person_info',
            name='Sex',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Famale')], max_length=4, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/zhangli/reader', verbose_name='头像'),
        ),
    ]
