# Generated by Django 2.2.5 on 2019-12-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20191209_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian_info',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='phone',
        ),
    ]
