# Generated by Django 2.2.5 on 2019-12-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20191209_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_info',
            name='ID',
        ),
        migrations.AddField(
            model_name='person_info',
            name='id',
            field=models.AutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
