# Generated by Django 2.2.5 on 2019-12-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_person_info_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='readerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=13, verbose_name='读者类型名')),
                ('bookNum', models.CharField(max_length=3, verbose_name='读者类型可借书籍')),
            ],
        ),
    ]
