# Generated by Django 2.2.5 on 2019-12-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_readertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_info',
            name='Sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=4, verbose_name='性别'),
        ),
    ]
