# Generated by Django 2.2.5 on 2019-12-10 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20191209_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'ordering': ['inTime'], 'verbose_name': '读者', 'verbose_name_plural': '读者'},
        ),
    ]
