# Generated by Django 2.2.5 on 2019-12-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20191210_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='photo',
        ),
    ]
