# Generated by Django 2.2.5 on 2019-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_remove_reader_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='inTime',
            field=models.DateField(verbose_name='登记日期'),
        ),
    ]
