# Generated by Django 2.2.5 on 2019-12-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20191210_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='photo',
            field=models.ImageField(blank=True, upload_to='readerimg', verbose_name='头像'),
        ),
    ]
