# Generated by Django 2.2.5 on 2019-12-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_reader_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/readerimg', verbose_name='头像'),
        ),
    ]
