# Generated by Django 2.2.5 on 2019-12-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20191213_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='photo',
            field=models.ImageField(blank=True, upload_to='readerimg', verbose_name='头像'),
        ),
    ]
