# Generated by Django 2.2.5 on 2019-12-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20191213_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='inTime',
            field=models.DateField(default='2019-12-19', verbose_name='登记日期'),
        ),
    ]
