# Generated by Django 2.1 on 2019-12-03 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0005_auto_20191202_2003'),
        ('search', '0002_booktype_info_ebook_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookback_info',
            fields=[
                ('bcID', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='图书归还事务ID')),
                ('backTime', models.DateTimeField(verbose_name='借阅时间')),
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Reader')),
                ('bookID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.book_info')),
                ('librarian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian_info_bookback', to='login.librarian_info')),
            ],
        ),
        migrations.CreateModel(
            name='bookborrow_info',
            fields=[
                ('brID', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='图书借阅事务ID')),
                ('borrowTime', models.DateTimeField(verbose_name='借阅时间')),
                ('expirationTime', models.DateTimeField(verbose_name='应归还时间')),
                ('ifBack', models.BooleanField(default=False, verbose_name='是否归还')),
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Reader')),
                ('bookID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.book_info')),
                ('librarian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian_info_bookborrow', to='login.librarian_info')),
            ],
        ),
    ]
