# Generated by Django 2.1 on 2019-12-05 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person_info',
            fields=[
                ('Sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('Name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='reader_info',
            fields=[
                ('person_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='librarian.person_info')),
                ('telNumber', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('readertypeName', models.CharField(blank=True, max_length=30, verbose_name='读者类型名称')),
                ('bookNumber', models.IntegerField(verbose_name='书籍上限')),
            ],
            bases=('librarian.person_info',),
        ),
    ]
