# Generated by Django 2.2.5 on 2019-12-18 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecbooklistInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=50)),
                ('bookAuthor', models.CharField(max_length=20)),
                ('bpublisher', models.CharField(max_length=30)),
                ('bpubTime', models.DateField()),
                ('bookISBN', models.CharField(max_length=10)),
                ('bookIntroduction', models.TextField()),
                ('RecTime', models.DateField(default=django.utils.timezone.now)),
                ('RecIdentity', models.CharField(max_length=20)),
                ('RecDepartment', models.CharField(max_length=50)),
                ('RecName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-RecTime',),
            },
        ),
    ]
