# Generated by Django 2.2.5 on 2019-12-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0002_auto_20191225_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recbooklistinfo',
            name='bpubTime',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
