# Generated by Django 2.2.6 on 2019-12-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0003_auto_20191226_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administerName', models.CharField(max_length=50)),
                ('telnumber', models.CharField(max_length=20)),
                ('contactsb', models.CharField(max_length=30)),
            ],
        ),
    ]
