# Generated by Django 2.2.5 on 2019-12-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0003_auto_20191225_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recbooklistinfo',
            name='RecName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Reader'),
        ),
    ]
