# Generated by Django 2.2.6 on 2019-12-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participate', '0004_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': '联系方式', 'verbose_name_plural': '联系方式'},
        ),
        migrations.AlterModelOptions(
            name='recbooklistinfo',
            options={'ordering': ('-RecTime',), 'verbose_name': '读者推荐', 'verbose_name_plural': '读者推荐'},
        ),
    ]
