# Generated by Django 2.1 on 2019-12-03 08:10

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=256, verbose_name='类别名称')),
                ('categorySlug', models.CharField(db_index=True, max_length=256, verbose_name='类别网址')),
                ('side_display', models.BooleanField(default=False, verbose_name='导航显示')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'ordering': ['categoryName'],
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=256, verbose_name='标题')),
                ('serviceSlug', models.CharField(max_length=200, unique=True, verbose_name='网址')),
                ('serviceContent', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('servicePublished', models.BooleanField(default=True, verbose_name='正式发布')),
                ('servicePubdate', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('serviceAuthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('serviceCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category', verbose_name='归属类别')),
            ],
            options={
                'verbose_name': '服务指南',
                'verbose_name_plural': '服务指南',
            },
        ),
    ]
