# Generated by Django 2.2.5 on 2019-11-27 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0006_auto_20191119_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='readerSearchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='查询时间')),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Book', verbose_name='ISBN')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Reader', verbose_name='读者')),
            ],
            options={
                'verbose_name': '我的查询历史',
                'verbose_name_plural': '我的查询历史',
            },
        ),
        migrations.CreateModel(
            name='readerLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('In_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='加入时间')),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Book', verbose_name='ISBN')),
                ('reader', models.ForeignKey(default='51', on_delete=django.db.models.deletion.CASCADE, to='library.Reader', verbose_name='读者')),
            ],
            options={
                'verbose_name': '我的图书馆',
                'verbose_name_plural': '我的图书馆',
            },
        ),
    ]
