# Generated by Django 2.2.5 on 2019-12-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerCenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerlibrary',
            name='defBookTpe',
            field=models.CharField(default='文学', max_length=200, verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='readerlibrary',
            name='In_date',
            field=models.DateField(default='2019-12-17', verbose_name='加入时间'),
        ),
    ]
