# Generated by Django 2.2.5 on 2019-12-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readerCenter', '0002_auto_20191217_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readerlibrary',
            old_name='defBookTpe',
            new_name='defBookType',
        ),
    ]
