# Generated by Django 2.2.5 on 2019-12-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerCenter', '0004_auto_20191217_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerlibrary',
            name='defBookType',
            field=models.CharField(default='我的图书分区', max_length=200, verbose_name='加入时间'),
        ),
    ]
