# Generated by Django 2.2.5 on 2019-12-18 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('readerCenter', '0005_auto_20191217_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerlibrary',
            name='In_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='加入时间'),
        ),
    ]
