# Generated by Django 2.2.6 on 2019-12-26 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('infoCenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rank_info',
            fields=[
                ('rankName', models.CharField(max_length=50, verbose_name='排行榜名称')),
                ('rankID', models.AutoField(primary_key=True, serialize=False)),
                ('pubTime', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('rankIntro', models.TextField(default='', verbose_name='栏目简介')),
                ('rankDisplay', models.BooleanField(default=True, verbose_name='正式发布')),
            ],
            options={
                'verbose_name': '排行榜',
                'verbose_name_plural': '排行榜',
                'ordering': ['pubTime'],
            },
        ),
        migrations.CreateModel(
            name='rank_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookOrder', models.IntegerField(default='0', verbose_name='图书序号')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.book_info')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoCenter.rank_info')),
            ],
            options={
                'verbose_name': '排行榜内图书',
                'verbose_name_plural': '排行榜内图书',
                'ordering': ['bookOrder'],
            },
        ),
    ]
