# Generated by Django 2.2.5 on 2019-12-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoCenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle_info',
            name='bookViews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
