# Generated by Django 2.1 on 2019-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookReser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readerId', models.CharField(max_length=256, verbose_name='读者号')),
                ('book', models.CharField(max_length=256, verbose_name='图书名')),
                ('bookId', models.CharField(max_length=256, verbose_name='图书编号')),
                ('returnTime', models.CharField(max_length=256, verbose_name='还书时间')),
                ('place', models.CharField(max_length=256, verbose_name='地点')),
            ],
        ),
    ]
