# Generated by Django 2.1 on 2019-12-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='cdId',
            field=models.CharField(default='1', max_length=256, verbose_name='光盘号'),
        ),
    ]
