# Generated by Django 2.1 on 2019-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booktype_info',
            fields=[
                ('btID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='图书类型ID')),
                ('btName', models.CharField(max_length=50, verbose_name='图书类型的名字')),
                ('bookType', models.BooleanField(default=True, verbose_name='可外借/馆内阅读')),
            ],
        ),
        migrations.CreateModel(
            name='ebook_info',
            fields=[
                ('ebookID', models.IntegerField(primary_key=True, serialize=False, verbose_name='图书财产ID')),
                ('ebookName', models.CharField(max_length=70, verbose_name='书名')),
                ('ebookAuthor', models.CharField(blank=True, max_length=30, verbose_name='作者')),
                ('ebookTranslator', models.CharField(blank=True, max_length=30, verbose_name='译者')),
                ('ebookPress', models.CharField(max_length=70, verbose_name='出版社')),
                ('ebookIntime', models.DateTimeField(verbose_name='图书入库时间')),
                ('ebookISBN', models.CharField(max_length=10, verbose_name='书的isbn号')),
                ('ebookPage', models.IntegerField(blank=True, verbose_name='图书页码')),
                ('ebookResource', models.CharField(max_length=200, verbose_name='电子图书资源内容的存储地址')),
            ],
        ),
    ]
