# Generated by Django 2.2.5 on 2019-11-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_info',
            name='bookID',
        ),
    ]
