# Generated by Django 2.2.5 on 2019-12-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_booktype_info_ebook_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='price',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=8, verbose_name='书籍价格'),
        ),
    ]
