# Generated by Django 2.2.5 on 2019-12-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20191213_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='cover',
            field=models.ImageField(blank=True, default='null', upload_to='bookcover', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='page',
            field=models.CharField(blank=True, max_length=255, verbose_name='图书页码'),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='price',
            field=models.CharField(max_length=20, null=True, verbose_name='价格'),
        ),
    ]
