# Generated by Django 2.2.5 on 2019-12-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_book_info_bookviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookentity_info',
            name='booksearchID',
            field=models.CharField(max_length=10, verbose_name='索书号'),
        ),
    ]
