# Generated by Django 2.2.5 on 2019-12-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_bookentity_info_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookentity_info',
            name='ISBN',
        ),
    ]
