# Generated by Django 2.2.5 on 2019-12-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_remove_bookentity_info_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookentity_info',
            name='bookID',
        ),
        migrations.AddField(
            model_name='bookentity_info',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
