# Generated by Django 2.2.5 on 2019-12-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20191219_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='bookID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.bookEntity_info'),
            preserve_default=False,
        ),
    ]
